### ISSUE TITLE
Who is in charge of merging the pull requests?

### ISSUE THREAD

**Issue by AndreasHassing** [bndn/scrum#5]
For this repo, who will merge pull requests that are deemed as "done"/"OK"? The Scrum master?

**Comment by AndreasHassing** [comment]
@kasperisager, @MGApcDev

**Comment by MGApcDev** [comment]
I don't think it matters that much, either me or @kasperisager is fine, for the pr's currently open I'm waiting to merge them, so on Friday we can go through them and change anything we feel should be changed.
Regardless, I'll keep my eyes on the scrum repo, to ensure any pr created eventually gets closed.

**Comment by kasperisager** [comment]
Finalising them tomorrow sounds like a plan, then we can rebase and merge.
